benchmarking:
  random_state: 42
  estimators:
    KNeighborsClassifier:
      name: KNeighborsClassifier
      estimator: sklearn.neighbors.KNeighborsClassifier
      hyperparameters:
        init:
          n_neighbors:
            - 1
            - 5
            - 1e2
          algorithm:
            - brute
          n_jobs:
            - -1
            - 1
      metrics:
        - accuracy_score
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
            random_state: 42
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
            random_state: 42
          n_features: 2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    daal4py_KNeighborsClassifier:
      inherit: KNeighborsClassifier
      estimator: daal4py.sklearn.neighbors.KNeighborsClassifier

    KNeighborsClassifier_kd_tree:
      name: KNeighborsClassifier_kd_tree
      estimator: sklearn.neighbors.KNeighborsClassifier
      hyperparameters:
        init:
          n_neighbors:
            - 1
            - 5
            - 1e2
          algorithm:
            - kd_tree
          n_jobs:
            - -1
            - 1
      metrics:
        - accuracy_score
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
            random_state: 42
          n_features: 10
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
            random_state: 42
          n_features: 2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    daal4py_KNeighborsClassifier_kd_tree:
      inherit: KNeighborsClassifier_kd_tree
      estimator: daal4py.sklearn.neighbors.KNeighborsClassifier

    KMeans_tall:
      name: KMeans_tall
      estimator: sklearn.cluster.KMeans
      hyperparameters:
        init:
          init:
            - k-means++
            - random
          algorithm:
            - full
          n_clusters:
            - 3
          max_iter:
            - 30
          n_init:
            - 1
          tol:
            - 1e-16
      metrics:
        - adjusted_rand_score
      datasets:
        - sample_generator: sklearn.datasets.make_blobs
          params:
            random_state: 42
            cluster_std: 20.0
            centers: 200
          n_features: 2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_blobs
          params:
            random_state: 42
            cluster_std: 20.0
            centers: 200
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    daal4py_KMeans_tall:
      inherit: KMeans_tall
      estimator: daal4py.sklearn.cluster.KMeans

    KMeans_short:
      name: KMeans_short
      estimator: sklearn.cluster.KMeans
      hyperparameters:
        init:
          init:
            - k-means++
            - random
          algorithm:
            - full
          n_clusters:
            - 300
          max_iter:
            - 30
          n_init:
            - 1
          tol:
            - 1e-16
      metrics:
        - adjusted_rand_score
      datasets:
        - sample_generator: sklearn.datasets.make_blobs
          params:
            random_state: 42
            cluster_std: 20.0
            centers: 200
          n_features: 2
          n_samples_train:
            - 1e4
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_blobs
          params:
            random_state: 42
            cluster_std: 20.0
            centers: 200
          n_features: 1e2
          n_samples_train:
            - 1e4
          n_samples_test:
            - 1
            - 1e3

    daal4py_KMeans_short:
      inherit: KMeans_short
      estimator: daal4py.sklearn.cluster.KMeans

    LogisticRegression:
      name: LogisticRegression
      estimator: sklearn.linear_model.LogisticRegression
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
            random_state: 42
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
            random_state: 42
          n_features: 1e4
          n_samples_train:
            - 1e3
          n_samples_test:
            - 1
            - 1e2

    daal4py_LogisticRegression:
      inherit: LogisticRegression
      estimator: daal4py.sklearn.linear_model.LogisticRegression

    Ridge:
      name: Ridge
      estimator: sklearn.linear_model.Ridge
      datasets:
        - sample_generator: sklearn.datasets.make_regression
          params:
            n_informative: 10
            random_state: 42
          n_features: 1e3
          n_samples_train:
            - 1e3
          n_samples_test:
            - 1
            - 1e2
        - sample_generator: sklearn.datasets.make_regression
          params:
            n_informative: 10
            random_state: 42
          n_features: 1e2
          n_samples_train:
            - 1e4
          n_samples_test:
            - 1
            - 1e3

    daal4py_Ridge:
      inherit: Ridge
      estimator: daal4py.sklearn.linear_model.Ridge

    HistGradientBoostingClassifier:
      name: HistGradientBoostingClassifier
      estimator: sklearn.ensemble.HistGradientBoostingClassifier
      experimental: sklearn.experimental.enable_hist_gradient_boosting
      time_budget: 300
      max_nb_fits: 20
      hyperparameters:
        init:
        init:
          learning_rate:
            - 0.01
            - 0.05
            - 0.1
            - 0.5
            - 1.
          n_iter_no_change:
            - 1
            - 3
            - 5
            - 10
            - 30
            - 50
          max_leaf_nodes:
            - 2
            - 3
            - 5
            - 20
            - 30
            - 50
          max_iter:
            - 30
            - 100
            - 300
            - 1000
          max_bins:
            - 32
            - 64
            - 128
            - 255
          min_samples_leaf:
            - 2
            - 10
            - 20
            - 100
            - 200
            - 1000
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 5
            n_informative: 5
            n_redundant: 0
            random_state: 42
          n_features: 1e2
          n_samples_train:
            - 1e6
          n_samples_test:
            - 1
            - 1e3

    lightgbm_HistGradientBoostingClassifier:
      inherit: HistGradientBoostingClassifier
      estimator: lightgbm.LGBMClassifier

reporting:
  n_cols: 2
  estimators:
    KNeighborsClassifier:
      name: KNeighborsClassifier
      against_lib: daal4py
      split_bars:
        - n_jobs
      compare:
        - accuracy_score

    KNeighborsClassifier_kd_tree:
      name: KNeighborsClassifier_kd_tree
      against_lib: daal4py
      split_bars:
        - n_jobs
      compare:
        - accuracy_score

    KMeans_tall:
      name: KMeans_tall
      against_lib: daal4py
      compare:
        - n_iter
        - adjusted_rand_score

    KMeans_short:
      name: KMeans_short
      against_lib: daal4py
      compare:
        - n_iter
        - adjusted_rand_score

    LogisticRegression:
      name: LogisticRegression
      against_lib: daal4py

    Ridge:
      name: Ridge
      against_lib: daal4py

    HistGradientBoostingClassifier:
      name: HistGradientBoostingClassifier
      against_lib: lightgbm
