benchmarking:
  random_seed: 42

  common_datasets:
    gradient_boosting:
      sample_generator: sklearn.datasets.make_classification
      params:
        n_classes: 5
        n_informative: 5
        n_redundant: 0
      n_features: 1e2
      n_samples_train:
        - 1e3
        - 1e5
      n_samples_test:
        - 1e3
        - 1e5

  estimators:
    KNeighborsClassifier_brute_force:
      name: KNeighborsClassifier_brute_force
      estimator: sklearn.neighbors.KNeighborsClassifier
      benchmarking_method: hp_match
      predict_with_onnx: False
      parameters:
        init:
          n_neighbors:
            - 1
            - 5
            - 100
          algorithm:
            - brute
          n_jobs:
            - -1
      metrics: []
      datasets:
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 2
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 100
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1
        - sample_generator: sklearn.datasets.make_classification
          params:
            n_classes: 2
            n_redundant: 0
          n_features: 500
          n_samples_train:
            - 1e5
          n_samples_test:
            - 1

    sklearnex_KNeighborsClassifier_brute_force:
      inherit: KNeighborsClassifier_brute_force
      estimator: sklearnex.neighbors.KNeighborsClassifier


hp_match_reporting:
  sklearnex:
    n_cols: 2
    estimators:
      KNeighborsClassifier_brute_force:
        name: KNeighborsClassifier_brute_force
        other_library: sklearnex
        split_bars_by_parameters:
          - n_jobs

      KNeighborsClassifier_kd_tree:
        name: KNeighborsClassifier_kd_tree
        other_library: sklearnex
        split_bars_by_parameters:
          - n_jobs

      KMeans_tall:
        name: KMeans_tall
        other_library: sklearnex

      KMeans_short:
        name: KMeans_short
        other_library: sklearnex

      LogisticRegression:
        name: LogisticRegression
        other_library: sklearnex

      Ridge:
        name: Ridge
        other_library: sklearnex

  onnx:
    n_cols: 2
    relevant_functions:
      - kneighbors
    estimators:
      KNeighborsClassifier_brute_force:
        name: KNeighborsClassifier_brute_force
        other_library: onnx
        split_bars_by_parameters:
          - n_jobs

      HistGradientBoostingClassifier_best:
        name: HistGradientBoostingClassifier_best
        other_library: onnx

hpo_reporting:
  speedup_thresholds:
    - 0.735
    - 0.77
    - 0.805
  estimators:
    HistGradientBoostingClassifier:
      lib: sklearn
      legend: scikit-learn
      color: blue

    LGBMClassifier:
      lib: lightgbm
      color: red

    XGBClassifier:
      lib: xgboost
      color: green

    CatBoostClassifier_lossguide:
      lib: catboost
      legend: catboost lossguide
      color: purple

    CatBoostClassifier_symmetric:
      lib: catboost
      legend: catboost symmetric
      color: orange
