name: sklbench
channels:
  - conda-forge
  - intel
dependencies:
  - python=3.8
  - black
  - pandas
  - pyyaml
  - plotly
  - jupyter
  - matplotlib
  - qgrid
  - viztracer
  - joblib
  - click
  - lightgbm
  - xgboost
  - pip
  - pip:
      - --pre
      - --index-url https://pypi.anaconda.org/scipy-wheels-nightly/simple
      - scikit-learn
