name: sklbench
channels:
  - conda-forge
  - intel
dependencies:
  - pandas
  - pyyaml
  - plotly
  - pip
  - pip:
      - --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn
  - scikit-learn-intelex
  - jupyter
  - qgrid
  - viztracer
  - joblib
  - click
