name: Run benchmarks

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISHED_BASE_URL: https://mbatoul.github.io/sklearn_benchmarks/
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install minimal dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade protobuf

      - name: Install specific dependencies
        run: |
          pip install pytest lightgbm xgboost catboost scikit-learn-intelex
          pip install --pre --extra-index https://pypi.anaconda.org/scipy-wheels-nightly/simple scikit-learn --upgrade

      - name: Set config vars for parallelism
        run: |
          export NUM_CORES=`python -c "import joblib; print(joblib.cpu_count())"`
          export MKL_NUM_THREADS=$NUM_CORES
          export OMP_NUM_THREADS=$NUM_CORES
          export OPENBLAS_NUM_THREADS=$NUM_CORES

      - name: Run benchmark suite
        run: python -m sklearn_benchmarks --config config.yml --run_profiling --fast

      # - name: Run test suite
      #   run: pytest sklearn_benchmarks/tests

      - name: Copy configuration file in results folder
        run: cp config.yml ./results

      - name: Remove profiling files above 100mb
        run: python scripts/remove_heavy_files.py

      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results

      - name: Convert notebook to html
        run: |
          jupyter nbconvert --to html --execute --output results/index.html index.ipynb
          jupyter nbconvert --to html --execute --output results/scikit_learn_intelex_vs_scikit_learn.html scikit_learn_intelex_vs_scikit_learn.ipynb
          jupyter nbconvert --to html --execute --output results/onnx_vs_scikit_learn.html onnx_vs_scikit_learn.ipynb
          jupyter nbconvert --to html --execute --output results/gradient_boosting.html gradient_boosting.ipynb

      - name: Download docs folder
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: results
