name: Run benchmarks

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLISHED_BASE_URL: https://mbatoul.github.io/sklearn_benchmarks/
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: sklbench
          environment-file: environment.yml
          channels: conda-forge,intel
          channel-priority: flexible
          use-only-tar-bz2: true

      - name: Set config vars for parallelism
        run: |
          export NUM_CORES=`python -c "import joblib; print(joblib.cpu_count())"`
          export MKL_NUM_THREADS=$NUM_CORES
          export OMP_NUM_THREADS=$NUM_CORES
          export OPENBLAS_NUM_THREADS=$NUM_CORES

      - name: Run benchmark suite
        run: python -m sklearn_benchmarks --config config.yml --run_profiling --fast

      # - name: Run test suite
      #   run: pytest sklearn_benchmarks/tests

      - name: Copy configuration file in results folder
        run: cp config.yml ./results

      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results

      - name: Remove profiling files above 100mb
        run: python scripts/remove_heavy_files.py

      - name: Convert notebook to html
        run: |
          jupyter nbconvert --to html --execute --output results/index.html index.ipynb
          jupyter nbconvert --to html --execute --output results/scikit_learn_intelex_vs_scikit_learn.html scikit_learn_intelex_vs_scikit_learn.ipynb
          jupyter nbconvert --to html --execute --output results/onnx_vs_scikit_learn.html onnx_vs_scikit_learn.ipynb
          jupyter nbconvert --to html --execute --output results/gradient_boosting.html gradient_boosting.ipynb

      - name: Download docs folder
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: results
