name: scikit-learn benchmark suite

on:
  push:
    branches: [implement_gradient_boosting_benchmark]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKLEARN_RESULTS_BASE_URL: https://mbatoul.github.io/sklearn_benchmarks/
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: sklbench
          environment-file: environment.yml
          channels: conda-forge,intel
          channel-priority: flexible
          use-only-tar-bz2: true

      - name: Set config vars for parallelism
        run: |
          export NUM_CORES=`python -c "import joblib; print(joblib.cpu_count())"`
          export MKL_NUM_THREADS=$NUM_CORES
          export OMP_NUM_THREADS=$NUM_CORES
          export OPENBLAS_NUM_THREADS=$NUM_CORES

      - name: Run benchmark suite
        run: python -m sklearn_benchmarks --e HistGradientBoostingClassifier --e lightgbm

      - name: Convert notebook to html
        run: |
          jupyter nbconvert --to html --execute --output results/index.html reporting_randomized_search.ipynb

      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results
